# Python CircleCI 2.1 configuration file
version: 2.1
orbs:
    codecov: codecov/codecov@1.0.4
jobs:
    build:
        docker:
            - image: circleci/python:2.7.15
        working_directory: ~/repo
        environment:
            CODECOV_TOKEN: "0fe7267f-08ce-4059-85a5-aa048b999962"
        steps:
            - checkout
            - run:
                name: install dependencies
                command: pip install --user -r requirements.txt

            - run:
                name: run tests
                command: |
                    source setup.sh
                    python -m pytest --cov-report=xml --cov=zdb tests/

            - codecov/upload:
                file: coverage.xml
