database:
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00000/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00001/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00002/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00003/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00004/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00005/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00006/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00007/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00008/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00009/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00010/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00011/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00012/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00013/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00014/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00015/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00016/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00017/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00018/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00019/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00020/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00021/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00022/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00023/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00024/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00025/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00026/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00027/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00028/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00029/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00030/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00031/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00032/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00033/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00034/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00035/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00036/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00037/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00038/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00039/result.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_ZJetsToNuNu/results/task_00040/result.db"
query:
    template: "SELECT {columns} FROM Events WHERE {selection} GROUP BY {groupby}"
    aliases:
        Weight_MET_MC:
            "WeightXsLumi*WeightQcdEwk*WeightPU*WeightPreFiring*WeightMETTrig*WeightOneMinusElectronVetoNoSelectionIdIsoVeto*WeightOneMinusElectronSelectionIdIsoTight*WeightOneMinusElectronVetoReco*WeightOneMinusMuonVetoNoSelectionIdLoose*WeightOneMinusMuonVetoNoSelectionIsoLoose*WeightOneMinusMuonSelectionIdTight*WeightOneMinusMuonSelectionIsoTight*WeightOneMinusPhotonVetoIdLoose*WeightOneMinusPhotonVetoPixelSeedVeto*WeightOneMinusTauSelectionIdTight*WeightOneMinusJetBVetoIdMedium"
    histograms:
        METnoX_pt:
            columns:
                - "parent, CAST(METnoX_pt/50. as int)*50 as METnoX_pt_low"
                - "SUM({Weight_MET_MC}) as nominal"
                - "SUM({Weight_MET_MC}*LHEScaleWeight0) as qcdscale0"
                - "SUM({Weight_MET_MC}*LHEScaleWeight1) as qcdscale1"
                - "SUM({Weight_MET_MC}*LHEScaleWeight2) as qcdscale2"
                - "SUM({Weight_MET_MC}*LHEScaleWeight3) as qcdscale3"
                - "SUM({Weight_MET_MC}*LHEScaleWeight4) as qcdscale4"
                - "SUM({Weight_MET_MC}*LHEScaleWeight5) as qcdscale5"
                - "SUM({Weight_MET_MC}*LHEScaleWeight6) as qcdscale6"
                - "SUM({Weight_MET_MC}*LHEScaleWeight7) as qcdscale7"
                - "SUM({Weight_MET_MC}*LHEScaleWeight8) as qcdscale8"
                - "SUM({Weight_MET_MC}*LHEPdfWeight0) as pdf0"
                - "SUM({Weight_MET_MC}*LHEPdfWeight1) as pdf1"
                - "SUM({Weight_MET_MC}*LHEPdfWeight2) as pdf2"
                - "SUM({Weight_MET_MC}*LHEPdfWeight3) as pdf3"
                - "SUM({Weight_MET_MC}*LHEPdfWeight4) as pdf4"
                - "SUM({Weight_MET_MC}*LHEPdfWeight5) as pdf5"
                - "SUM({Weight_MET_MC}*LHEPdfWeight6) as pdf6"
                - "SUM({Weight_MET_MC}*LHEPdfWeight7) as pdf7"
                - "SUM({Weight_MET_MC}*LHEPdfWeight8) as pdf8"
                - "SUM({Weight_MET_MC}*LHEPdfWeight9) as pdf9"
                - "SUM({Weight_MET_MC}*LHEPdfWeight10) as pdf10"
                - "SUM({Weight_MET_MC}*LHEPdfWeight11) as pdf11"
                - "SUM({Weight_MET_MC}*LHEPdfWeight12) as pdf12"
                - "SUM({Weight_MET_MC}*LHEPdfWeight13) as pdf13"
                - "SUM({Weight_MET_MC}*LHEPdfWeight14) as pdf14"
                - "SUM({Weight_MET_MC}*LHEPdfWeight15) as pdf15"
                - "SUM({Weight_MET_MC}*LHEPdfWeight16) as pdf16"
                - "SUM({Weight_MET_MC}*LHEPdfWeight17) as pdf17"
                - "SUM({Weight_MET_MC}*LHEPdfWeight18) as pdf18"
                - "SUM({Weight_MET_MC}*LHEPdfWeight19) as pdf19"
                - "SUM({Weight_MET_MC}*LHEPdfWeight20) as pdf20"
                - "SUM({Weight_MET_MC}*LHEPdfWeight21) as pdf21"
                - "SUM({Weight_MET_MC}*LHEPdfWeight22) as pdf22"
                - "SUM({Weight_MET_MC}*LHEPdfWeight23) as pdf23"
                - "SUM({Weight_MET_MC}*LHEPdfWeight24) as pdf24"
                - "SUM({Weight_MET_MC}*LHEPdfWeight25) as pdf25"
                - "SUM({Weight_MET_MC}*LHEPdfWeight26) as pdf26"
                - "SUM({Weight_MET_MC}*LHEPdfWeight27) as pdf27"
                - "SUM({Weight_MET_MC}*LHEPdfWeight28) as pdf28"
                - "SUM({Weight_MET_MC}*LHEPdfWeight29) as pdf29"
                - "SUM({Weight_MET_MC}*LHEPdfWeight30) as pdf30"
                - "SUM({Weight_MET_MC}*LHEPdfWeight31) as pdf31"
                - "SUM({Weight_MET_MC}*LHEPdfWeight32) as pdf32"
                - "SUM({Weight_MET_MC}*LHEPdfWeight33) as pdf33"
                - "SUM({Weight_MET_MC}*LHEPdfWeight34) as pdf34"
                - "SUM({Weight_MET_MC}*LHEPdfWeight35) as pdf35"
                - "SUM({Weight_MET_MC}*LHEPdfWeight36) as pdf36"
                - "SUM({Weight_MET_MC}*LHEPdfWeight37) as pdf37"
                - "SUM({Weight_MET_MC}*LHEPdfWeight38) as pdf38"
                - "SUM({Weight_MET_MC}*LHEPdfWeight39) as pdf39"
                - "SUM({Weight_MET_MC}*LHEPdfWeight40) as pdf40"
                - "SUM({Weight_MET_MC}*LHEPdfWeight41) as pdf41"
                - "SUM({Weight_MET_MC}*LHEPdfWeight42) as pdf42"
                - "SUM({Weight_MET_MC}*LHEPdfWeight43) as pdf43"
                - "SUM({Weight_MET_MC}*LHEPdfWeight44) as pdf44"
                - "SUM({Weight_MET_MC}*LHEPdfWeight45) as pdf45"
                - "SUM({Weight_MET_MC}*LHEPdfWeight46) as pdf46"
                - "SUM({Weight_MET_MC}*LHEPdfWeight47) as pdf47"
                - "SUM({Weight_MET_MC}*LHEPdfWeight48) as pdf48"
                - "SUM({Weight_MET_MC}*LHEPdfWeight49) as pdf49"
                - "SUM({Weight_MET_MC}*LHEPdfWeight50) as pdf50"
                - "SUM({Weight_MET_MC}*LHEPdfWeight51) as pdf51"
                - "SUM({Weight_MET_MC}*LHEPdfWeight52) as pdf52"
                - "SUM({Weight_MET_MC}*LHEPdfWeight53) as pdf53"
                - "SUM({Weight_MET_MC}*LHEPdfWeight54) as pdf54"
                - "SUM({Weight_MET_MC}*LHEPdfWeight55) as pdf55"
                - "SUM({Weight_MET_MC}*LHEPdfWeight56) as pdf56"
                - "SUM({Weight_MET_MC}*LHEPdfWeight57) as pdf57"
                - "SUM({Weight_MET_MC}*LHEPdfWeight58) as pdf58"
                - "SUM({Weight_MET_MC}*LHEPdfWeight59) as pdf59"
                - "SUM({Weight_MET_MC}*LHEPdfWeight60) as pdf60"
                - "SUM({Weight_MET_MC}*LHEPdfWeight61) as pdf61"
                - "SUM({Weight_MET_MC}*LHEPdfWeight62) as pdf62"
                - "SUM({Weight_MET_MC}*LHEPdfWeight63) as pdf63"
                - "SUM({Weight_MET_MC}*LHEPdfWeight64) as pdf64"
                - "SUM({Weight_MET_MC}*LHEPdfWeight65) as pdf65"
                - "SUM({Weight_MET_MC}*LHEPdfWeight66) as pdf66"
                - "SUM({Weight_MET_MC}*LHEPdfWeight67) as pdf67"
                - "SUM({Weight_MET_MC}*LHEPdfWeight68) as pdf68"
                - "SUM({Weight_MET_MC}*LHEPdfWeight69) as pdf69"
                - "SUM({Weight_MET_MC}*LHEPdfWeight70) as pdf70"
                - "SUM({Weight_MET_MC}*LHEPdfWeight71) as pdf71"
                - "SUM({Weight_MET_MC}*LHEPdfWeight72) as pdf72"
                - "SUM({Weight_MET_MC}*LHEPdfWeight73) as pdf73"
                - "SUM({Weight_MET_MC}*LHEPdfWeight74) as pdf74"
                - "SUM({Weight_MET_MC}*LHEPdfWeight75) as pdf75"
                - "SUM({Weight_MET_MC}*LHEPdfWeight76) as pdf76"
                - "SUM({Weight_MET_MC}*LHEPdfWeight77) as pdf77"
                - "SUM({Weight_MET_MC}*LHEPdfWeight78) as pdf78"
                - "SUM({Weight_MET_MC}*LHEPdfWeight79) as pdf79"
                - "SUM({Weight_MET_MC}*LHEPdfWeight80) as pdf80"
                - "SUM({Weight_MET_MC}*LHEPdfWeight81) as pdf81"
                - "SUM({Weight_MET_MC}*LHEPdfWeight82) as pdf82"
                - "SUM({Weight_MET_MC}*LHEPdfWeight83) as pdf83"
                - "SUM({Weight_MET_MC}*LHEPdfWeight84) as pdf84"
                - "SUM({Weight_MET_MC}*LHEPdfWeight85) as pdf85"
                - "SUM({Weight_MET_MC}*LHEPdfWeight86) as pdf86"
                - "SUM({Weight_MET_MC}*LHEPdfWeight87) as pdf87"
                - "SUM({Weight_MET_MC}*LHEPdfWeight88) as pdf88"
                - "SUM({Weight_MET_MC}*LHEPdfWeight89) as pdf89"
                - "SUM({Weight_MET_MC}*LHEPdfWeight90) as pdf90"
                - "SUM({Weight_MET_MC}*LHEPdfWeight91) as pdf91"
                - "SUM({Weight_MET_MC}*LHEPdfWeight92) as pdf92"
                - "SUM({Weight_MET_MC}*LHEPdfWeight93) as pdf93"
                - "SUM({Weight_MET_MC}*LHEPdfWeight94) as pdf94"
                - "SUM({Weight_MET_MC}*LHEPdfWeight95) as pdf95"
                - "SUM({Weight_MET_MC}*LHEPdfWeight96) as pdf96"
                - "SUM({Weight_MET_MC}*LHEPdfWeight97) as pdf97"
                - "SUM({Weight_MET_MC}*LHEPdfWeight98) as pdf98"
                - "SUM({Weight_MET_MC}*LHEPdfWeight99) as pdf99"
                - "SUM({Weight_MET_MC}*LHEPdfWeight100) as pdf100"
                - "SUM({Weight_MET_MC}*LHEPdfWeight101) as pdf101"
                - "SUM({Weight_MET_MC}*LHEPdfWeight102) as pdf102"
            selection:
                Monojet: "Cutflow_Monojet==1"
                MonojetQCD: "Cutflow_MonojetQCD==1"
                SingleMuon: "Cutflow_SingleMuon==1"
                SingleMuonQCD: "Cutflow_SingleMuonQCD==1"
                DoubleMuon: "Cutflow_DoubleMuon==1"
                SingleElectron: "Cutflow_SingleElectron==1"
                SingleElectronQCD: "Cutflow_SingleElectronQCD==1"
                DoubleElectron: "Cutflow_DoubleElectron==1"
                SingleTau: "Cutflow_SingleTau==1"
            groupby:
                "parent, CAST(METnoX_pt/50. as int)*50"
