query:
    index: ["selection", "parent", "LeptonIsElectron", "LeptonIsMuon", "LeptonIsTau", "nGenTauL", "METnoX_pt_low"]
    template: "SELECT {columns} FROM Events WHERE {selection} GROUP BY {groupby}"
    aliases:
        Weight_MET_MC:
            "WeightXsLumi*WeightQcdEwk*WeightPU*WeightPreFiring*WeightMETTrig*WeightOneMinusElectronVetoNoSelectionIdIsoVeto*WeightOneMinusElectronSelectionIdIsoTight*WeightOneMinusElectronVetoReco*WeightOneMinusMuonVetoNoSelectionIdLoose*WeightOneMinusMuonVetoNoSelectionIsoLoose*WeightOneMinusMuonSelectionIdTight*WeightOneMinusMuonSelectionIsoTight*WeightOneMinusPhotonVetoIdLoose*WeightOneMinusPhotonVetoPixelSeedVeto*WeightOneMinusTauSelectionIdTight*WeightOneMinusJetBVetoIdMedium"
    histograms:
        METnoX_pt:
            columns:
                - "parent, LeptonIsElectron, LeptonIsMuon, LeptonIsTau, nGenTauL, CAST(METnoX_pt/10. as int)*10 as METnoX_pt_low"
                - "SUM({Weight_MET_MC}) as nominal"
                - "SUM({Weight_MET_MC}*LHEScaleWeight0) as qcdscale0"
                - "SUM({Weight_MET_MC}*LHEPdfWeight0) as pdf0"
            selection:
                Monojet: "Cutflow_Monojet==1"
                SingleMuon: "Cutflow_SingleMuon==1"
            groupby:
                "parent, LeptonIsElectron, LeptonIsMuon, LeptonIsTau, nGenTauL, CAST(METnoX_pt/10. as int)*10"
database:
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_MCPdfVariations/sqlite_collector/DYJetsToLL/result_00100.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_MCPdfVariations/sqlite_collector/DYJetsToLL/result_00300.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_MCPdfVariations/sqlite_collector/EWKV2Jets/result_00019.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_MCPdfVariations/sqlite_collector/G1Jet/result_00100.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_MCPdfVariations/sqlite_collector/G1Jet/result_00236.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_MCPdfVariations/sqlite_collector/QCD/result_00199.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_MCPdfVariations/sqlite_collector/WJetsToLNu/result_00100.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_MCPdfVariations/sqlite_collector/WJetsToLNu/result_00339.db"
    - "/vols/cms/sdb15/Analysis/ZinvWidth/databases/201904_Apr/06_MCPdfVariations/sqlite_collector/ZJetsToNuNu/result_00030.db"
